name: GAT Push

on:
  push:
    paths:
      - .github/workflows/gat-**.yml
      - 'gat/**'
jobs:
  test:
    name: Push Job
    runs-on: ubuntu-latest
    steps:
      - name: Push OK step
        run: echo Push OK!
